name: Build and Release build Image
on:
  push:
    paths:
    - "build-base/*"

jobs: 
  release:
    name: Build and Release Build Image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Log in to the Github Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all    
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
 
    - name: Build for build
      uses: docker/build-push-action@v2
      with:
        context: build-base
        push: true
        tags: ghcr.io/iaacautomation/devops-tools/build:latest
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        build-args: DISTRO=bookworm-slim
        cache-from: type=gha
        cache-to: type=gha,mode=max
