name: Build and Release diagnose Image
on:
  push:
    paths:
    - "diagnose/**"

jobs: 
  release:
    name: Build and Release Build Image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Log in to the Github Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all    
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
 
    - name: Build for diagnose
      if: github.event_name == 'push'
      uses: docker/build-push-action@v2
      with:
        context: diagnose
        push: true
        tags: ghcr.io/iaacautomation/devops-tools/diagnose:test
        platforms: linux/amd64,linux/arm64
        build-args: DISTRO=bookworm-slim
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and Push image for deploy
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: ghcr.io/iaacautomation/devops-tools/diagnose:test
        dst: ghcr.io/iaacautomation/devops-tools/diagnose:latest
