name: Release
on:
  push:
    branches:
      - main
jobs: 
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: get-changed-dirs
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Set Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_ACCOUNT }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_ACCOUNT }}
        password: ${{ secrets.GITLAB_TOKEN }} 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Extract metadata (tags, labels) for Docker
      id: meta-deploy
      uses: docker/metadata-action@v3
      with:
        images: ${{ github.repository }}//deploy

    - name: Build and push Docker image for deploy
      uses: docker/build-push-action@v2
      with:
        context: deploy
        push: true
        tags: |
          ${{ steps.meta-deploy.outputs.tags }}
          registry.gitlab.com/${{ steps.meta-deploy.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        build-args: DISTRO=bookworm

    - name: Extract metadata (tags, labels) for Docker
      id: meta-diagnose
      uses: docker/metadata-action@v3
      with:
        images: ${{ github.repository }}//diagnose

    - name: Build and push Docker image for diagnostics
      uses: docker/build-push-action@v2
      with:
        context: diagnose
        push: true
        tags: |
          ${{ steps.meta-diagnose.outputs.tags }}
          registry.gitlab.com/${{ steps.meta-diagnose.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        build-args: DISTRO=bookworm