name: Push Images
on:
  push:
    tags:

jobs:     
  push_image_dockerhub:
    if: contains(github.ref,'tag')
    name: Push Deploy Image to Dockerhub
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: Log in to the Docker Container registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_ACCOUNT }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: ghcr.io/iaacautomation/devops-tools/deploy:test
        dst: |
          ${{ secrets.DOCKERHUB_ACCOUNT }}/deploy:${{steps.tag.outputs.tag}}
          ${{ secrets.DOCKERHUB_ACCOUNT }}/deploy:latest

  push_image_github:
    if: contains(github.ref,'tag')
    name: Push Images to github
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: Log in to the Github Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Push Image for Build
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: ghcr.io/iaacautomation/devops-tools/deploy:test
        dst: |
          ghcr.io/iaacautomation/devops-tools/deploy:${{steps.tag.outputs.tag}}
          ghcr.io/iaacautomation/devops-tools/deploy:latest

    - name: Push Image for Build
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: ghcr.io/iaacautomation/devops-tools/build:test
        dst: ghcr.io/iaacautomation/devops-tools/build:latest

    - name: Push Image for Diagnose
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: ghcr.io/iaacautomation/devops-tools/diagnose:test
        dst: ghcr.io/iaacautomation/devops-tools/diagnose:latest

  push_image_gitlab:
    if: contains(github.ref,'tag')
    name: Push Deploy Image to Gitlab
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: Log in to the Gitlab Container registry
      uses: docker/login-action@v1
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_ACCOUNT }}
        password: ${{ secrets.GITLAB_TOKEN }} 

    - uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: ghcr.io/iaacautomation/devops-tools/deploy:test
        dst: |
          ${{ secrets.GITLAB_REGISTRY_PATH }}/deploy:${{steps.tag.outputs.tag}}
          ${{ secrets.GITLAB_REGISTRY_PATH }}/deploy:latest
