name: Build and Release Deploy Image
on:
  push:
    paths:
      - 'whisparr/**'
      - '.github/workflows/whisparr.yaml'
  schedule:
      - cron: '0 0 * * 0'

jobs: 
  release:
    name: Build and Release Deploy Image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Log in to the Github Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all    
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push images
      uses: docker/build-push-action@v5
      with:
        context: whisparr
        push: true
        tags: ghcr.io/iaacautomation/whisparr:latest
        platforms: linux/amd64 ,linux/arm64
        build-args: DISTRO=${{ vars.BASE_IMAGE }}
        cache-from: type=gha
